BaSP - MR-21: ID references on Class
BaSP-m2023/nai-megarocket-server pull request #44
Opened 2023-05-19 03:06 UTC by CavalloFede

Added id references on class to trainer and activity in clasess model 
Added .populate to getAllClasses in classes controller to show it works
Added .populate to getClassId classes controller to show it works
Changed the validation from string to an idObject of trainers and activitys in clasess joi validation

2023-05-19 14:44 UTC, IvanJukonis requested changes
The relationships have been established correctly. The only inconvenience found is that it allows you to add an activity or a trainer with a valid ID that does not exist in the database, causing both fields to remain NULL. 

CHANGES RELETED TO OTHER TICKETS. PR APPROVED.

2023-05-19 14:50 UTC, IvanJukonis approved these changes

2023-05-19 14:55 UTC, CavalloFede reviewed
fixed

2023-05-21 05:16 UTC, nailaghigo approved these changes
🚀

2023-05-21 20:36 UTC, merged