BaSP-MR-30: Test admin put delete
BaSP-m2023/nai-megarocket-server pull request #47
Opened 2023-05-20 15:48 UTC by IgnacioGalceran

Added data in Admin.js file in seed folder.
Added tests to put and delete endpoints.

2023-05-20 18:17 UTC, Micaela-Rossi commented on src/tests/admins.test.js
> +describe('PUT /api/admins', () => {
Here must said DELETE instead of PUT

2023-05-20 20:46 UTC, Eliezer-Alberto commented on src/tests/admins.test.js
> +describe('PUT /api/admins', () => {
Apart from that, It is all fine!..

2023-05-21 04:15 UTC, nailaghigo requested changes
🎸

2023-05-21 04:15 UTC, nailaghigo commented on src/tests/admins.test.js
> +    expect(typeof response.body.data).toBe('object');
Are we sure that we are testing that our data is empty? I think we could use the following example 
`expect(response.body.data).toEqual({})`

Check if we have to replace something similar throughout the code

2023-05-21 04:15 UTC, nailaghigo commented on src/tests/admins.test.js
> +    expect(response.body.data).toBe(undefined);
We could use `.toBeUndefined()` jest matcher here.

2023-05-22 07:59 UTC, Eliezer-Alberto commented on src/tests/admins.test.js
> +    expect(response.body.data).toBe(undefined);
Could it be used `.toBeUndefined();` jest matcher here..?

2023-05-22 23:55 UTC, Eliezer-Alberto approved these changes
I think It's all fine!..

2023-05-23 00:28 UTC, nailaghigo approved these changes
🚀

2023-05-24 21:50 UTC, merged