BaSP-HOTFIX-MR-107: create consitency between all validations and fixed bugs
BaSP-m2023/nai-megarocket-server pull request #65
Opened 2023-06-10 23:40 UTC by fernandofernandezuy

Pull Request Description:

This pull request addresses several modifications and bug fixes in the server. The following aspects have been modified:

Fixed a bug that allowed the creation of a super admin with numbers or spaces in their name. This issue has been resolved by implementing proper validation and rejecting any invalid characters in the super admin's name.

Fixed a bug that allowed the creation of an admin with numbers or spaces in their name or last name. Similar to the previous fix, appropriate validation has been added to prevent the creation of admins with invalid characters in their name or last name.

Fixed a bug that prevented the editing of an admin. The issue has been resolved by identifying and correcting the underlying cause that was causing the editing functionality to fail.

Fixed a bug related to updating activities. The bug has been identified and fixed, ensuring that activities can now be updated without any issues.

Created consistency between all validations. All validation processes across the server have been reviewed and standardized to ensure uniformity and maintain a consistent approach to data validation.

Added functionality in the controllers to prevent send the same data in the edit of almost all entitys(missing member and classes)

2023-06-11 00:50 UTC, AleMac17 approved these changes

2023-06-11 00:53 UTC, AleMac17 commented on src/controllers/class.js
>          return res.status(404).json({
Shouldn't this be a 400 error? since 404 is for not fount cases

2023-06-11 00:56 UTC, AleMac17 requested changes

2023-06-11 00:56 UTC, AleMac17 commented on src/controllers/super-admins.js
> +        return applyResponse(res, 404, 'There is nothing to change', undefined, true);
shouldn't this be a 400 error? since 404 is for not found cases

2023-06-11 17:18 UTC, fernandofernandezuy commented
![](https://github.trello.services/images/mini-trello-icon.png) [[HOTFIX] - Server Validations](https://trello.com/c/0avxF8Os/107-hotfix-server-validations)

2023-06-15 16:45 UTC, lorenzomauro59 approved these changes
NICE job Fer!

2023-06-16 13:31 UTC, AleMac17 approved these changes

2023-06-16 13:34 UTC, merged